config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "settings/preferences"
  get "settings/integrations"
  patch "settings/update_preferences"
  get "feature/index"
  get "report/index"

  root to: "home#index"

  resources :monthly_summaries
  resources :budgets
  resources :payments
  resources :invoices
  resources :categories
  resources :transactions
  resources :accounts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :account
end

app/models/monthly_summary.rb
class MonthlySummary < ApplicationRecord
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :account
  belongs_to :invoice
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :setting
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monthly_summaries_controller.rb
class MonthlySummariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_monthly_summary, only: %i[ show edit update destroy ]

  # GET /monthly_summaries or /monthly_summaries.json
  def index
    @monthly_summaries = MonthlySummary.all
  end

  # GET /monthly_summaries/1 or /monthly_summaries/1.json
  def show
  end

  # GET /monthly_summaries/new
  def new
    @monthly_summary = MonthlySummary.new
  end

  # GET /monthly_summaries/1/edit
  def edit
  end

  # POST /monthly_summaries or /monthly_summaries.json
  def create
    @monthly_summary = MonthlySummary.new(monthly_summary_params)

    respond_to do |format|
      if @monthly_summary.save
        format.html { redirect_to @monthly_summary, notice: "Monthly summary was successfully created." }
        format.json { render :show, status: :created, location: @monthly_summary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monthly_summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_summaries/1 or /monthly_summaries/1.json
  def update
    respond_to do |format|
      if @monthly_summary.update(monthly_summary_params)
        format.html { redirect_to @monthly_summary, notice: "Monthly summary was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @monthly_summary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monthly_summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_summaries/1 or /monthly_summaries/1.json
  def destroy
    @monthly_summary.destroy!

    respond_to do |format|
      format.html { redirect_to monthly_summaries_path, notice: "Monthly summary was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_summary
      @monthly_summary = MonthlySummary.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def monthly_summary_params
      params.expect(monthly_summary: [ :user_id, :month, :year, :total_income, :total_expense, :balance ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_active(path)
    current_page?(path) ? "active" : ""
  end

  def check(theme)
    puts "#{theme} =================================================="
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_helper.rb
module FeatureHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/monthly_summaries_helper.rb
module MonthlySummariesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/monthly_summaries/_form.html.erb
<%= form_with(model: monthly_summary) do |form| %>
  <% if monthly_summary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(monthly_summary.errors.count, "error") %> prohibited this monthly_summary from being saved:</h2>

      <ul>
        <% monthly_summary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.text_field :month %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :total_income, style: "display: block" %>
    <%= form.text_field :total_income %>
  </div>

  <div>
    <%= form.label :total_expense, style: "display: block" %>
    <%= form.text_field :total_expense %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/monthly_summaries/_monthly_summary.html.erb
<div id="<%= dom_id monthly_summary %>">
  <p>
    <strong>User:</strong>
    <%= monthly_summary.user_id %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= monthly_summary.month %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= monthly_summary.year %>
  </p>

  <p>
    <strong>Total income:</strong>
    <%= monthly_summary.total_income %>
  </p>

  <p>
    <strong>Total expense:</strong>
    <%= monthly_summary.total_expense %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= monthly_summary.balance %>
  </p>

</div>

app/views/monthly_summaries/edit.html.erb
<% content_for :title, "Editing monthly summary" %>

<h1>Editing monthly summary</h1>

<%= render "form", monthly_summary: @monthly_summary %>

<br>

<div>
  <%= link_to "Show this monthly summary", @monthly_summary %> |
  <%= link_to "Back to monthly summaries", monthly_summaries_path %>
</div>

app/views/monthly_summaries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Monthly summaries" %>

<h1>Monthly summaries</h1>

<div id="monthly_summaries">
  <% @monthly_summaries.each do |monthly_summary| %>
    <%= render monthly_summary %>
    <p>
      <%= link_to "Show this monthly summary", monthly_summary %>
    </p>
  <% end %>
</div>

<%= link_to "New monthly summary", new_monthly_summary_path %>

app/views/monthly_summaries/new.html.erb
<% content_for :title, "New monthly summary" %>

<h1>New monthly summary</h1>

<%= render "form", monthly_summary: @monthly_summary %>

<br>

<div>
  <%= link_to "Back to monthly summaries", monthly_summaries_path %>
</div>

app/views/monthly_summaries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monthly_summary %>

<div>
  <%= link_to "Edit this monthly summary", edit_monthly_summary_path(@monthly_summary) %> |
  <%= link_to "Back to monthly summaries", monthly_summaries_path %>

  <%= button_to "Destroy this monthly summary", @monthly_summary, method: :delete %>
</div>