config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "settings/preferences"
  get "settings/integrations"
  patch "settings/update_preferences"
  get "feature/index"
  get "report/index"

  root to: "home#index"

  resources :monthly_summaries
  resources :budgets
  resources :payments
  resources :invoices
  resources :categories
  resources :transactions
  resources :accounts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :account
end

app/models/monthly_summary.rb
class MonthlySummary < ApplicationRecord
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :account
  belongs_to :invoice
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :setting
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_active(path)
    current_page?(path) ? "active" : ""
  end

  def check(theme)
    puts "#{theme} =================================================="
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_helper.rb
module FeatureHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navbar.html.erb
<div id="navbarContainer">
  <nav class="navbar navbar-dark navbar-expand-lg" id="mainNavbar-<%= theme %>">
    <div class="container-fluid">
      <!-- Title do navbar primary -->
      <div>
        <a class="navbar-brand" href="#">Dashboard</a>
      </div>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <!-- ms-auto empurra para a direita -->
        <ul class="navbar-nav ms-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu">
              <%= link_to "Preferences", settings_preferences_path, class: "dropdown-item" %>
              <li><a class="dropdown-item" href="#">Integrations</a></li>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to "Features", feature_index_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Admin</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_sidebar.html.erb
<!-- Nav secundary vertical mais o conteudo ao lado -->
<div class="d-flex">
  <nav class="navbar flex-column vh-90 p-3 sidebar" style="width: 240px;" id="sidebarMenu">
    <div class="navbar-nav d-flex h-100 w-100">
      <div class="d-flex flex-column gap-3">
        <%= link_to root_path, class: "nav-link-#{theme} d-flex align-items-center gap-2 #{nav_active(root_path)}" do %>
          <i class="bi bi-speedometer2"></i>
          Dashboard
        <% end %>

        <%= link_to accounts_path, class: "nav-link-#{theme} d-flex align-items-center gap-2 #{nav_active(accounts_path)}" do %>
          <i class="bi bi-bank"></i>
          Accounts
        <% end %>

        <%= link_to transactions_path, class: "nav-link-#{theme} d-flex align-items-center gap-2 #{nav_active(transactions_path)}" do %>
          <i class="bi bi-arrow-left-right"></i>
          Transactions
        <% end %>


        <%= link_to budgets_path, class: "nav-link-#{theme} d-flex align-items-center gap-2 #{nav_active(budgets_path)}" do %>
          <i class="bi bi-sliders"></i>
          Budgets
        <% end %>

        <%= link_to invoices_path, class: "nav-link-#{theme} d-flex align-items-center gap-2 #{nav_active(invoices_path)}" do %>
          <i class="bi bi-receipt"></i>
          Invoices
        <% end %>
      </div>
    </div>
  </nav>