config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "settings/preferences"
  get "settings/integrations"
  patch "settings/update_preferences"
  get "feature/index"
  get "report/index"

  root to: "home#index"

  resources :monthly_summaries
  resources :budgets
  resources :payments
  resources :invoices
  resources :categories
  resources :transactions
  resources :accounts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :account
end

app/models/monthly_summary.rb
class MonthlySummary < ApplicationRecord
  belongs_to :user
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :account
  belongs_to :invoice
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :setting
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: "Payment was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy!

    respond_to do |format|
      format.html { redirect_to payments_path, notice: "Payment was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.expect(payment: [ :amount, :payment_date, :payment_method, :account_id, :invoice_id ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_active(path)
    current_page?(path) ? "active" : ""
  end

  def check(theme)
    puts "#{theme} =================================================="
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_helper.rb
module FeatureHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :payment_date, style: "display: block" %>
    <%= form.date_field :payment_date %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.text_field :account_id %>
  </div>

  <div>
    <%= form.label :invoice_id, style: "display: block" %>
    <%= form.text_field :invoice_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>Payment date:</strong>
    <%= payment.payment_date %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= payment.payment_method %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= payment.account_id %>
  </p>

  <p>
    <strong>Invoice:</strong>
    <%= payment.invoice_id %>
  </p>

</div>

app/views/payments/edit.html.erb
<% content_for :title, "Editing payment" %>

<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/new.html.erb
<% content_for :title, "New payment" %>

<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>